function nlToSql(naturalQuery) {
    const query = naturalQuery.toLowerCase();

    if (query.includes("total revenue")) {
        return {
            sql: "SELECT SUM(revenue) AS total_revenue FROM sales;",
            explanation: "Calculates the total revenue from all sales."
        };
    } else if (query.includes("total sales")) {
        return {
            sql: "SELECT COUNT(*) AS total_sales FROM sales;",
            explanation: "Counts the total number of sales transactions."
        };
    } else if (query.match(/sales in (\w+ \d{4})/)) {
        const match = query.match(/sales in (\w+ \d{4})/);
        return {
            sql: `SELECT COUNT(*) AS total_sales FROM sales WHERE date LIKE '%${match[1]}%';`,
            explanation: `Counts the number of sales made in ${match[1]}.`
        };
    } else if (query.match(/total revenue for (\w+)/)) {
        const match = query.match(/total revenue for (\w+)/);
        return {
            sql: `SELECT SUM(revenue) AS total_revenue FROM sales WHERE product = '${match[1]}';`,
            explanation: `Calculates total revenue from sales of ${match[1]}.`
        };
    } else if (query.includes("average revenue")) {
        return {
            sql: "SELECT AVG(revenue) AS average_revenue FROM sales;",
            explanation: "Finds the average revenue per sale."
        };
    } else if (query.includes("highest revenue")) {
        return {
            sql: "SELECT MAX(revenue) AS highest_revenue FROM sales;",
            explanation: "Finds the highest single sale revenue."
        };
    } else if (query.includes("lowest revenue")) {
        return {
            sql: "SELECT MIN(revenue) AS lowest_revenue FROM sales;",
            explanation: "Finds the lowest single sale revenue."
        };
    } else if (query.includes("total customers")) {
        return {
            sql: "SELECT COUNT(DISTINCT customer_id) AS total_customers FROM sales;",
            explanation: "Counts the number of unique customers."
        };
    } else if (query.includes("most sold product")) {
        return {
            sql: "SELECT product, COUNT(*) AS total_sold FROM sales GROUP BY product ORDER BY total_sold DESC LIMIT 1;",
            explanation: "Finds the product with the highest sales count."
        };
    } else if (query.includes("least sold product")) {
        return {
            sql: "SELECT product, COUNT(*) AS total_sold FROM sales GROUP BY product ORDER BY total_sold ASC LIMIT 1;",
            explanation: "Finds the product with the lowest sales count."
        };
    } else if (query.includes("sales by category")) {
        return {
            sql: "SELECT category, COUNT(*) AS total_sales FROM sales GROUP BY category;",
            explanation: "Counts sales for each product category."
        };
    } else if (query.includes("total revenue by category")) {
        return {
            sql: "SELECT category, SUM(revenue) AS total_revenue FROM sales GROUP BY category;",
            explanation: "Calculates total revenue for each product category."
        };
    } else if (query.match(/total revenue in (\d{4})/)) {
        const match = query.match(/total revenue in (\d{4})/);
        return {
            sql: `SELECT SUM(revenue) AS total_revenue FROM sales WHERE YEAR(date) = ${match[1]};`,
            explanation: `Calculates total revenue for the year ${match[1]}.`
        };
    } else if (query.match(/sales by employee (\w+)/)) {
        const match = query.match(/sales by employee (\w+)/);
        return {
            sql: `SELECT COUNT(*) AS total_sales FROM sales WHERE employee = '${match[1]}';`,
            explanation: `Counts the number of sales made by employee ${match[1]}.`
        };
    } else if (query.match(/revenue by employee (\w+)/)) {
        const match = query.match(/revenue by employee (\w+)/);
        return {
            sql: `SELECT SUM(revenue) AS total_revenue FROM sales WHERE employee = '${match[1]}';`,
            explanation: `Calculates total revenue generated by employee ${match[1]}.`
        };
    } else if (query.includes("top 5 customers")) {
        return {
            sql: "SELECT customer_id, SUM(revenue) AS total_spent FROM sales GROUP BY customer_id ORDER BY total_spent DESC LIMIT 5;",
            explanation: "Finds the top 5 customers based on total spending."
        };
    } else if (query.includes("top 5 products")) {
        return {
            sql: "SELECT product, COUNT(*) AS total_sold FROM sales GROUP BY product ORDER BY total_sold DESC LIMIT 5;",
            explanation: "Finds the top 5 best-selling products."
        };
    } else if (query.includes("total transactions")) {
        return {
            sql: "SELECT COUNT(*) AS total_transactions FROM sales;",
            explanation: "Counts the total number of sales transactions."
        };
    }

    throw new Error("Unsupported query format.");
}

module.exports = { nlToSql };
